---
name: Sample
description: "Rule which sends an email when an email from mine.ishan@gmail.com is received"
pack: demo10
enabled: false
trigger:
  type: demo10.imap.message
  parameters: {}
criteria:
  trigger.from:
    pattern: ishuwww084@gmail.com
    type: contains
action:
  ref: core.sendmail
  parameters:
    body: 'We received an email'
    to: ishuwww084@gmail.com
    from: ishuwww084@gmail.com
    subject: 'Email Received'
