---
name: Sample
description: "Rule which sends an email when an email from mine.ishan@gmail.com is received"
pack: demo10
enabled: true
trigger:
  type: demo10.smtp.message
  parameters: {}
criteria:
  trigger.from:
    pattern: ishuwww084@gmail.com
    type: contains
   action: 
        ref: demo10.sendmail
        parameters:
          account: ishuwww084
          message: 'We received an email'
          email_to: ishuwww084@gmail.com
          email_from: stackstorm.alert@gmail.com
          subject: 'Email Received'
