---
name: Sample
description: "Rule which sends an email when an email from mine.ishan@gmail.com is received"
pack: demo10
enabled: true
trigger:
  type: demo10.smtp.message
  parameters: {}
criteria:
  trigger.subject:
    pattern: ishuwww084@gmail.com
    type: contains
action: 
  ref: demo10.action1
  parameters:
    account: ishuwww084
    email_from: stackstorm.alert@gmail.com
    email_to: ishuwww084@gmail.com
    message: 'hi there senson working properly'
    subject: 'VM created'
